export interface Country {
  code: string;
  name: string;
}

// 자주가는 국가 목록
export const frequentCountries: Country[] = [
  { code: 'JP', name: '일본' },
  { code: 'VN', name: '베트남' },
  { code: 'TH', name: '태국' },
  { code: 'TW', name: '대만' },
  { code: 'PH', name: '필리핀' },
  { code: 'GU', name: '괌' },
  { code: 'SG', name: '싱가포르' },
  { code: 'US', name: '미국' },
  { code: 'MY', name: '말레이시아' },
];

// 전체 국가 목록 (엑셀 B,D,F,H,J,L 열 순서와 동일)
export const allCountries: Country[] = [
  { code: 'GY', name: '가이아나' },
  { code: 'GP', name: '과들루프' },
  { code: 'GF', name: '기아나' },
  { code: 'MQ', name: '마르티니크' },
  { code: 'MS', name: '몬트세랫' },
  { code: 'BS', name: '바하마' },
  { code: 'VE', name: '베네수엘라(가입불가)' },
  { code: 'BO', name: '볼리비아' },
  { code: 'BR', name: '브라질' },
  { code: 'SR', name: '수리남' },
  { code: 'AR', name: '아르헨티나' },
  { code: 'HT', name: '아이티(가입불가)' },
  { code: 'EC', name: '에콰도르' },
  { code: 'UY', name: '우루과이' },
  { code: 'CO', name: '콜롬비아' },
  { code: 'TC', name: '터크스 케이커스 제도' },
  { code: 'PY', name: '파라과이' },
  { code: 'PE', name: '페루' },
  { code: 'PR', name: '푸에리토리코' },
  { code: 'GS', name: 'SOUTH GEORGIA AND THE SOUTH SANDWICH ISLANDS' },
  { code: 'GT', name: '과테말라' },
  { code: 'GD', name: '그레나다' },
  { code: 'NI', name: '니카라과' },
  { code: 'DM', name: '도미니카' },
  { code: 'DO', name: '도미니카공화국' },
  { code: 'MX', name: '멕시코' },
  { code: 'US', name: '미국' },
  { code: 'VI', name: '버진 아일랜드(미국령)' },
  { code: 'UM', name: '미국령 작은 섬' },
  { code: 'MI', name: '미드웨이' },
  { code: 'BB', name: '바베이도스' },
  { code: 'VG', name: '버진 아일랜드(영국령)' },
  { code: 'BZ', name: '벨리즈' },
  { code: 'KN', name: '세인트 키츠 네비스' },
  { code: 'LC', name: '세인트루시아' },
  { code: 'VC', name: '세인트빈센트그레나딘' },
  { code: 'AG', name: '안티구아 바부다' },
  { code: 'AI', name: '앙갈라' },
  { code: 'SV', name: '엘살바도르' },
  { code: 'HN', name: '온두라스' },
  { code: 'JM', name: '자메이카' },
  { code: 'CL', name: '칠레' },
  { code: 'CA', name: '캐나다' },
  { code: 'CR', name: '코스타리카' },
  { code: 'CU', name: '쿠바(가입불가)' },
  { code: 'TT', name: '트리니다드 토바고' },
  { code: 'PA', name: '파나마' },
  { code: 'JT', name: 'JOHNSTON IS' },
  { code: 'WK', name: 'WAKE ISLAND' },
  { code: 'NP', name: '네팔' },
  { code: 'TW', name: '대만(타이완)' },
  { code: 'TL', name: '동티모르' },
  { code: 'LA', name: '라오스' },
  { code: 'LB', name: '레바논(가입불가)' },
  { code: 'MO', name: '마카오' },
  { code: 'MY', name: '말레이시아' },
  { code: 'MV', name: '몰디브' },
  { code: 'MN', name: '몽골' },
  { code: 'MM', name: '미얀마(가입불가)' },
  { code: 'BH', name: '바레인(가입불가)' },
  { code: 'BD', name: '방글라데시' },
  { code: 'VN', name: '베트남' },
  { code: 'BT', name: '부탄' },
  { code: 'KP', name: '북한(가입불가)' },
  { code: 'BN', name: '브루나이' },
  { code: 'SA', name: '사우디아라비아(가입불가)' },
  { code: 'CY', name: '사이프러스' },
  { code: 'LK', name: '스리랑카' },
  { code: 'SY', name: '시리아(가입불가)' },
  { code: 'SG', name: '싱가포르' },
  { code: 'AE', name: '아랍에미리트공화국(가입불가)' },
  { code: 'AM', name: '아르메니아' },
  { code: 'AZ', name: '아제르바이젠' },
  { code: 'AF', name: '아프가니스탄(가입불가)' },
  { code: 'YE', name: '예멘(가입불가)' },
  { code: 'OM', name: '오만' },
  { code: 'JO', name: '요르단(가입불가)' },
  { code: 'UZ', name: '우즈베키스탄' },
  { code: 'IQ', name: '이라크(가입불가)' },
  { code: 'IR', name: '이란(가입불가)' },
  { code: 'IL', name: '이스라엘(가입불가)' },
  { code: 'IN', name: '인도' },
  { code: 'ID', name: '인도네시아' },
  { code: 'JP', name: '일본' },
  { code: 'GE', name: '조지아' },
  { code: 'CN', name: '중국' },
  { code: 'KZ', name: '카자흐스탄' },
  { code: 'QA', name: '카타르(가입불가)' },
  { code: 'KH', name: '캄보디아' },
  { code: 'KW', name: '쿠웨이트(가입불가)' },
  { code: 'KG', name: '키르키즈스탄' },
  { code: 'TJ', name: '타지키스탄' },
  { code: 'TH', name: '태국(타이)' },
  { code: 'TM', name: '투르크메니스탄' },
  { code: 'TR', name: '튀르키예(터키)' },
  { code: 'TI', name: '티모르' },
  { code: 'PK', name: '파키스탄(가입불가)' },
  { code: 'PS', name: '팔레스타인 자치구(가입불가)' },
  { code: 'PH', name: '필리핀' },
  { code: 'HK', name: '홍콩' },
  { code: 'GH', name: '가나' },
  { code: 'GA', name: '가봉' },
  { code: 'GM', name: '감비아' },
  { code: 'GN', name: '기니(가입불가)' },
  { code: 'GW', name: '기니비소' },
  { code: 'CV', name: '까뽀베르데' },
  { code: 'NA', name: '나미비아' },
  { code: 'NG', name: '나이지리아(가입불가)' },
  { code: 'ZA', name: '남아프리카공화국' },
  { code: 'NE', name: '니제르(가입불가)' },
  { code: 'LS', name: '레소토' },
  { code: 'RW', name: '르완다' },
  { code: 'LR', name: '라이베리아' },
  { code: 'LY', name: '리비아(가입불가)' },
  { code: 'MG', name: '마다가스카르' },
  { code: 'MW', name: '말라위' },
  { code: 'ML', name: '말리(가입불가)' },
  { code: 'MA', name: '모로코' },
  { code: 'MU', name: '모리셔스' },
  { code: 'MR', name: '모리타니아' },
  { code: 'MZ', name: '모잠비크' },
  { code: 'BJ', name: '베넹' },
  { code: 'BW', name: '보츠와나' },
  { code: 'BI', name: '부룬디' },
  { code: 'BF', name: '부르키나파소(가입불가)' },
  { code: 'ST', name: '생 토메 프린시페' },
  { code: 'EH', name: '서사하라' },
  { code: 'SN', name: '세네갈' },
  { code: 'SC', name: '세이쉘' },
  { code: 'SO', name: '소말리아(가입불가)' },
  { code: 'SD', name: '수단(가입불가)' },
  { code: 'SZ', name: '스와질랜드' },
  { code: 'SL', name: '시에라리온' },
  { code: 'AC', name: '아센션 섬' },
  { code: 'DZ', name: '알제리' },
  { code: 'AO', name: '앙골라' },
  { code: 'ER', name: '에리트리아' },
  { code: 'UG', name: '우간다' },
  { code: 'ET', name: '에티오피아' },
  { code: 'EG', name: '이집트' },
  { code: 'ZR', name: '자이레(가입불가)' },
  { code: 'ZM', name: '잠비아' },
  { code: 'GQ', name: '적도기니' },
  { code: 'CF', name: '중앙아프리카(가입불가)' },
  { code: 'DJ', name: '지부티' },
  { code: 'ZW', name: '짐바브웨' },
  { code: 'TD', name: '챠드(가입불가)' },
  { code: 'CM', name: '카메룬' },
  { code: 'KE', name: '케냐' },
  { code: 'KY', name: '케이멘군도' },
  { code: 'KM', name: '코모로' },
  { code: 'CI', name: '코트디브와르(가입불가)' },
  { code: 'CG', name: '콩고(가입불가)' },
  { code: 'CD', name: '콩고(자이레)(가입불가)' },
  { code: 'TZ', name: '탄자니아' },
  { code: 'TG', name: '토고' },
  { code: 'TN', name: '튀니지' },
  { code: 'TF', name: '프랑스령 남부지역' },
  { code: 'GU', name: '괌' },
  { code: 'NR', name: '나우루' },
  { code: 'NF', name: '노퍽아일랜드' },
  { code: 'NZ', name: '뉴질랜드' },
  { code: 'NC', name: '뉴칼레도니아' },
  { code: 'NU', name: '니웨(니우에)' },
  { code: 'MH', name: '마샬군도' },
  { code: 'FM', name: '미크로네시아' },
  { code: 'VU', name: '바누아투' },
  { code: 'MP', name: '북마리아나제도(사이판섬,티니안섬,로타섬 등)' },
  { code: 'WS', name: '서사모아' },
  { code: 'SB', name: '솔로몬군도' },
  { code: 'AW', name: '아루바' },
  { code: 'CC', name: '코코스섬' },
  { code: 'CK', name: '쿡아일랜드' },
  { code: 'CX', name: '크리스마스섬' },
  { code: 'KI', name: '키리바시' },
  { code: 'TK', name: '토켈라우' },
  { code: 'TO', name: '통가' },
  { code: 'TV', name: '투발루' },
  { code: 'PG', name: '파푸아뉴기니' },
  { code: 'PW', name: '팔라우' },
  { code: 'PF', name: '폴리네시아(프랑스령)' },
  { code: 'FJ', name: '피지' },
  { code: 'AU', name: '호주' },
  { code: 'CT', name: 'CANTON ENDERBURY' },
  { code: 'PC', name: 'CAROLINE IS' },
  { code: 'HM', name: 'HEARD AND MC DONALD ISLANDS' },
  { code: 'GR', name: '그리스' },
  { code: 'GL', name: '그린란드' },
  { code: 'NL', name: '네덜란드' },
  { code: 'NO', name: '노르웨이' },
  { code: 'DK', name: '덴마크' },
  { code: 'DE', name: '독일' },
  { code: 'LV', name: '라트비아' },
  { code: 'RU', name: '러시아(가입불가)' },
  { code: 'RE', name: '레위니옹' },
  { code: 'RO', name: '루마니아' },
  { code: 'LU', name: '룩셈부르크' },
  { code: 'LT', name: '리투아니아' },
  { code: 'LI', name: '리히텐슈타인' },
  { code: 'MK', name: '마케도니아' },
  { code: 'MC', name: '모나코' },
  { code: 'MD', name: '몰도바(가입불가)' },
  { code: 'MT', name: '몰타' },
  { code: 'PM', name: '미클롱 섬' },
  { code: 'VA', name: '바티칸' },
  { code: 'BM', name: '버뮤다' },
  { code: 'BE', name: '벨기에' },
  { code: 'BY', name: '벨라루스(가입불가)' },
  { code: 'BA', name: '보니스아 헤르체코비나' },
  { code: 'BG', name: '불가리아' },
  { code: 'SM', name: '산마리노' },
  { code: 'RS', name: '세르비아' },
  { code: 'SJ', name: '스발바르 얀마위엔섬' },
  { code: 'SE', name: '스웨덴' },
  { code: 'CH', name: '스위스' },
  { code: 'ES', name: '스페인' },
  { code: 'SK', name: '슬로바키아' },
  { code: 'SI', name: '슬로베니아' },
  { code: 'IS', name: '아이슬란드' },
  { code: 'IE', name: '아일랜드' },
  { code: 'AD', name: '안도라' },
  { code: 'AL', name: '알바니아' },
  { code: 'EE', name: '에스토니아' },
  { code: 'GB', name: '영국' },
  { code: 'AT', name: '오스트리아' },
  { code: 'UA', name: '우크라이나(가입불가)' },
  { code: 'WF', name: '월리스푸투나제도' },
  { code: 'YU', name: '유고' },
  { code: 'IT', name: '이탈리아' },
  { code: 'GI', name: '지브롤터' },
  { code: 'CZ', name: '체코' },
  { code: 'HR', name: '크로아티아' },
  { code: 'FO', name: '페로제도' },
  { code: 'PT', name: '포르투갈' },
  { code: 'FK', name: '포클랜드' },
  { code: 'PL', name: '폴란드' },
  { code: 'FR', name: '프랑스' },
  { code: 'FI', name: '핀란드' },
  { code: 'HU', name: '헝가리' },
  { code: 'BV', name: 'BOUVET ISLAND' },
  { code: 'IO', name: 'BRITISH INDIAN OCEAN TERRITORY' },
  { code: 'FX', name: 'FRANCE METROPOLITAN' },
  { code: 'YT', name: 'MAYOTTE' },
  { code: 'PN', name: 'PITCAIRN' },
];
